ALTER TABLE `#@__channeltype` CHANGE `nid` `nid` VARCHAR( 30 ) NOT NULL  default '';
ALTER TABLE `#@__conote` CHANGE `arcsource` `arcsource` VARCHAR( 50 )  NOT NULL default '';
ALTER TABLE `#@__addonsoft` Add `downloads` INT(11) NOT NULL default '0';
ALTER TABLE `#@__addonsoft` ADD INDEX ( `downloads` );

INSERT INTO `#@__admintype` VALUES (1, '信息发布员', 1, 't_AccList t_AccNew t_AccEdit t_AccDel a_AccNew a_AccList a_AccCheck a_MyList a_MyEdit a_MyDel sys_MdPwd sys_Feedback sys_MyUpload plus_留言簿模块');
INSERT INTO `#@__admintype` VALUES (5, '频道管理员', 1, 't_AccList t_AccNew t_AccEdit t_AccDel a_AccNew a_AccList a_AccEdit a_AccDel a_AccCheck a_MyList a_MyEdit a_MyDel a_MyCheck co_AddNote co_EditNote co_PlayNote co_ListNote co_ViewNote spec_New spec_List spec_Edit sys_MdPwd sys_Log sys_ArcTj sys_Source sys_Writer sys_Keyword sys_MakeHtml sys_Feedback sys_Upload sys_MyUpload member_List member_Edit plus_站内新闻发布 plus_友情链接模块 plus_留言簿模块 plus_投票模块 plus_广告管理 ');
INSERT INTO `#@__admintype` VALUES (10, '超级管理员', 1, 'admin_AllowAll ');

INSERT INTO `#@__arcatt` VALUES (1, '滚动显示');
INSERT INTO `#@__arcatt` VALUES (2, '头条推荐');
INSERT INTO `#@__arcatt` VALUES (3, '幻灯片显');
INSERT INTO `#@__arcatt` VALUES (5, '首页推荐');
INSERT INTO `#@__arcatt` VALUES (4, '首页滚动');

INSERT INTO `#@__arcrank` VALUES (1, 0, '开放浏览', 5, 0);
INSERT INTO `#@__arcrank` VALUES (2, -1, '待审核稿件', 0, 0);
INSERT INTO `#@__arcrank` VALUES (3, 10, '注册会员', 5, 0);
INSERT INTO `#@__arcrank` VALUES (4, 50, '中级会员', 5, 2500);
INSERT INTO `#@__arcrank` VALUES (5, 100, '高级会员', 5, 10000);
INSERT INTO `#@__arcrank` VALUES (6, 1000, '超级会员', 5, 1000000);


INSERT INTO `#@__channeltype` VALUES (1, 'article', '普通文章', '#@__archives', '#@__addonarticle', 'article_add.php', 'content_list.php', 'article_edit.php', 'article_add.php', 'content_list.php', 'article_edit.php', '<field:body itemname=''文章内容'' type=''htmltext'' isnull=''true'' default='''' rename='''' page=''split''/>', '', 1, 1, 1, -1, 10, 0, 0);
INSERT INTO `#@__channeltype` VALUES (2, 'image', '图片集', '#@__archives', '#@__addonimages', 'album_add.php', 'content_i_list.php', 'album_edit.php', 'album_add.php', 'content_list.php', 'album_edit.php', '<field:pagestyle itemname=''页面风格'' type=''number'' isnull=''true'' default=''2'' rename='''' notsend=''1'' />\r\n<field:imgurls itemname=''图片集合'' type=''img'' isnull=''true'' default='''' rename='''' page=''split''/>\r\n', '', 1, 1, 1, -1, 10, 0, 0);
INSERT INTO `#@__channeltype` VALUES (3, 'soft', '软件', '#@__archives', '#@__addonsoft', 'soft_add.php', 'content_i_list.php', 'soft_edit.php', 'soft_add.php', 'content_list.php', 'soft_edit.php', '<field:filetype islist=''1'' itemname=''文件类型'' type=''text'' isnull=''true'' default='''' rename='''' />\r\n<field:language islist=''1'' itemname=''语言'' type=''text'' isnull=''true'' default='''' rename='''' />\r\n<field:softtype islist=''1'' itemname=''软件类型'' type=''text'' isnull=''true'' default='''' rename='''' />\r\n<field:accredit islist=''1'' itemname=''授权方式'' type=''text'' isnull=''true'' default='''' rename='''' />\r\n<field:os islist=''1'' itemname=''操作系统'' type=''text'' isnull=''true'' default='''' rename='''' />\r\n<field:softrank  islist=''1'' itemname=''软件等级'' type=''int'' isnull=''true'' default=''3'' rename='''' function=''GetRankStar(@me)'' notsend=''1''/>\r\n<field:officialUrl  itemname=''官方网址'' type=''text'' isnull=''true'' default='''' rename='''' />\r\n<field:officialDemo itemname=''演示网址'' type=''text'' isnull=''true'' default='''' rename='''' />\r\n<field:softsize  itemname=''软件大小'' type=''text'' isnull=''true'' default='''' rename='''' />\r\n<field:softlinks  itemname=''软件地址'' type=''softlinks'' isnull=''true'' default='''' rename='''' />\r\n<field:introduce  itemname=''详细介绍'' type=''htmltext'' isnull=''trnue'' default='''' rename='''' />\r\n', 'filetype,language,softtype,accredit,os,softrank', 1, 1, 1, -1, 10, 0, 0);
INSERT INTO `#@__channeltype` VALUES (4, 'flash', 'Flash', '#@__archives', '#@__addonflash', 'flash_add.php', 'content_i_list.php', 'flash_edit.php', 'flash_add.php', 'content_list.php', 'flash_edit.php', '<field:filesize islist=''1'' itemname=''文件大小'' type=''text'' isnull=''true'' default=''1 MB'' rename='''' />\r\n<field:playtime islist=''1'' itemname=''播放时间'' type=''text'' isnull=''true'' default=''3 分钟'' rename='''' />\r\n<field:flashtype islist=''1'' itemname=''作品类型'' type=''text'' isnull=''true'' default='''' rename='''' />\r\n<field:flashrank islist=''1'' itemname=''作品等级'' type=''int'' isnull=''true'' default=''3'' rename='''' function=''GetRankStar(@me)'' notsend=''1''/>\r\n<field:width itemname=''文件宽度'' type=''int'' isnull=''true'' default=''500'' rename='''' />\r\n<field:height itemname=''文件高度'' type=''int'' isnull=''true'' default=''400'' rename='''' />\r\n<field:flashurl itemname=''文件网址'' type=''text'' isnull=''true'' default='''' rename='''' />\r\n\r\n', 'filesize,playtime,flashtype,flashrank', 1, 1, 1, -1, 10, 0, 0);
INSERT INTO `#@__channeltype` VALUES (-1, 'spec', '专题', '#@__archivesspec', '#@__addonspec', 'spec_add.php', 'content_s_list.php', 'spec_edit.php', '', '', '', '<field:note itemname=''节点内容'' type=''specialtopic'' isnull=''true'' default='''' rename=''''/>\r\n', '', 1, 1, 0, -1, 10, 0, 0);
INSERT INTO `#@__channeltype` VALUES (5, 'product', '产品', '#@__archives', '#@__addonproduct', 'archives_add.php', 'content_i_list.php', 'archives_edit.php', 'archives_add.php', 'content_list.php', 'archives_edit.php', '<field:assprice itemname="参考价格" autofield="1" notsend="0" type="float" isnull="true" islist="0" default="0" function="" maxlength="" page="">\r\n</field:assprice>\r\n\r\n<field:bigpic itemname="产品图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default="" function="" maxlength="200" page="">\r\n</field:bigpic>\r\n\r\n\r\n<field:model itemname="产品型号" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="" function="" maxlength="100" page="">\r\n</field:model>\r\n\r\n<field:sptype itemname="供应方式" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="" function="SelSpType(@me)" maxlength="10" page="">\r\n厂家直销,厂家批发,商家批发,商家零售,其它渠道</field:sptype>\r\n\r\n<field:cometime itemname="上市时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default="" function="" maxlength="" page="">\r\n</field:cometime>\r\n\r\n<field:brand itemname="产品品牌" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="" function="" maxlength="30" page="">\r\n</field:brand>\r\n\r\n<field:size itemname="产品规格" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="" function="" maxlength="50" page="">\r\n</field:size>\r\n\r\n<field:stuff itemname="产品材质" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="" function="" maxlength="100" page="">\r\n</field:stuff>\r\n\r\n<field:msg itemname="产品详细描述" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default="" function="" maxlength="" page="">\r\n</field:msg>\r\n', '', 1, 1, 1, -1, 10, 1, 0);
INSERT INTO `#@__channeltype` VALUES (-2, 'info', '分类信息', '#@__infos', '#@__addoninfos', 'info_add.php', 'info_list.php', 'info_edit.php', 'infoadd.php', 'content_list.php', 'infoedit.php', '<field:message itemname=''信息内容'' type=''htmltext'' isnull=''true'' default='''' rename='''' page=''''/>\r\n<field:contact itemname=''联系人'' type=''text'' isnull=''true'' default='''' rename='''' page=''''/>\r\n<field:phone itemname=''联系电话'' type=''text'' isnull=''true'' default='''' rename='''' page=''''/>\r\n<field:fax itemname=''传真'' type=''text'' isnull=''true'' default='''' rename='''' page=''''/>\r\n<field:email itemname=''电子邮箱'' type=''text'' isnull=''true'' default='''' rename='''' page=''''/>\r\n<field:qq itemname=''QQ'' type=''text'' isnull=''true'' default='''' rename='''' page=''''/>\r\n<field:msn itemname=''MSN'' type=''text'' isnull=''true'' default='''' rename='''' page=''''/>\r\n<field:address itemname=''地址'' type=''text'' isnull=''true'' default='''' rename='''' page=''''/>\r\n', '', 1, 1, 1, -1, 10, 2, 0);

INSERT INTO `#@__co_exrule` VALUES (1, 1, 'Dede文章模型', '当前系统', 1164939755, '{dede:note \r\n  rulename=''Dede文章模型''\r\n  etype=''当前系统''\r\n  tablename=''#@__archives,#@__addonarticle''\r\n  autofield=''ID''\r\n  synfield=''aid''\r\n  channelid=''1''\r\n/}\r\n{dede:field name=''typeid'' comment=''栏目ID'' intable=''#@__archives'' source=''value''}{tid}{/dede:field}\r\n{dede:field name=''sortrank'' comment=''排序级别'' intable=''#@__archives'' source=''function''}@me = time();{/dede:field}\r\n{dede:field name=''arcrank'' comment=''文档权限'' intable=''#@__archives'' source=''value''}{rank}{/dede:field}\r\n{dede:field name=''channel'' comment=''频道类型'' intable=''#@__archives'' source=''value''}{cid}{/dede:field}\r\n{dede:field name=''adminID'' comment=''管理员ID'' intable=''#@__archives'' source=''value''}{admin}{/dede:field}\r\n{dede:field name=''senddate'' comment=''录入时间'' intable=''#@__archives'' source=''value''}{senddate}{/dede:field}\r\n{dede:field name=''source'' comment=''文章来源'' intable=''#@__archives'' source=''value''}{source}{/dede:field}\r\n{dede:field name=''typeid'' comment=''栏目ID'' intable=''#@__addonarticle'' source=''value''}{tid}{/dede:field}\r\n{dede:field name=''pubdate'' comment=''发布时间'' intable=''#@__archives'' source=''function''}@me = ( @me!="" ? GetMkTime(@me) : time());{/dede:field}\r\n{dede:field name=''litpic'' comment=''缩略图'' intable=''#@__archives'' source=''function''}@me = @litpic;{/dede:field}\r\n{dede:field name=''title'' comment=''文章标题'' intable=''#@__archives'' source=''export''}{/dede:field}\r\n{dede:field name=''writer'' comment=''文章作者'' intable=''#@__archives'' source=''export''}{/dede:field}\r\n{dede:field name=''body'' comment=''文章内容'' intable=''#@__addonarticle'' source=''export''}{/dede:field}');

INSERT INTO `#@__flinktype` VALUES (1, '综合网站');
INSERT INTO `#@__flinktype` VALUES (2, '娱乐类');
INSERT INTO `#@__flinktype` VALUES (3, '教育类');
INSERT INTO `#@__flinktype` VALUES (4, '计算机类');
INSERT INTO `#@__flinktype` VALUES (5, '电子商务');
INSERT INTO `#@__flinktype` VALUES (6, '网上信息');
INSERT INTO `#@__flinktype` VALUES (7, '论坛类');
INSERT INTO `#@__flinktype` VALUES (8, '其它类型');

INSERT INTO `#@__homepageset` VALUES ('default/index.html', '../index.html');

INSERT INTO `#@__flink` VALUES (1, 1, 'http://www.dedecms.com', '织梦内容管理系统', '织梦内容管理系统（DEDECMS）--免费的PHP网站管理系统', '', 'http://www.dedecms.com/upimg/dedeflink.gif', '2008-01-19 11:31:29', 1, 2);

INSERT INTO `#@__member_time` VALUES (7, '一周');
INSERT INTO `#@__member_time` VALUES (30, '一个月');
INSERT INTO `#@__member_time` VALUES (90, '三个月');
INSERT INTO `#@__member_time` VALUES (183, '半年');
INSERT INTO `#@__member_time` VALUES (366, '一年');
INSERT INTO `#@__member_time` VALUES (32767, '终身');

INSERT INTO `#@__modules` VALUES (1, '问答模块', '1a1e82f369aebc58d24a18d9d2dfba2e', '1a1e82f369aebc58d24a18d9d2dfba2e.dev', 0);
INSERT INTO `#@__modules` VALUES (2, '书库模块', '589f328921a4b83fe8f12877e2be6c8d', '589f328921a4b83fe8f12877e2be6c8d.dev', 0);
INSERT INTO `#@__modules` VALUES (3, '圈子模块', '7898d3a521cacad9dce3fa9db19d6a1b', '7898d3a521cacad9dce3fa9db19d6a1b.dev', 0);

INSERT INTO `#@__plus` VALUES (1, '文件管理器', '<m:item name=''文件管理器'' link=''file_manage_main.php'' rank=''plus_文件管理器'' target=''main'' />', '织梦团队', 1, '');
INSERT INTO `#@__plus` VALUES (2, '站内新闻发布', '<m:item name=''站内新闻发布'' link=''mynews_main.php'' rank=''plus_站内新闻发布'' target=''main'' />', '织梦团队', 1, '');
INSERT INTO `#@__plus` VALUES (3, '友情链接模块', '<m:item name=''友情链接模块'' link=''friendlink_main.php'' rank=''plus_友情链接模块'' target=''main'' />', '织梦团队', 1, '');
INSERT INTO `#@__plus` VALUES (4, '留言簿模块', '<m:item name=''留言簿模块'' link=''catalog_do.php?dopost=guestbook'' rank=''plus_留言簿模块'' target=''main'' />', '织梦团队', 1, '');
INSERT INTO `#@__plus` VALUES (5, '投票模块', '<m:item name=''投票模块'' link=''vote_main.php'' rank=''plus_投票模块'' target=''main'' />', '织梦团队', 1, '');
INSERT INTO `#@__plus` VALUES (6, '论坛扩展', '<m:item name=''论坛扩展'' link=''bbs_addons.php'' rank=''plus_论坛扩展'' target=''main'' />', '织梦团队', 1, '');
INSERT INTO `#@__plus` VALUES (7, '广告管理', '<m:item name=''广告管理'' link=''ad_main.php'' rank=''plus_广告管理'' target=''main'' />', '织梦团队', 1, '');
INSERT INTO `#@__plus` VALUES (8, '正则规则测试器', '<m:item name=''正则规则测试器'' link=''ruletest.php'' rank=''plus_正则规则测试器'' target=''main'' />', '织梦团队', 1, 'ruletest.php');
INSERT INTO `#@__plus` VALUES (9, '随机模板防采集', '<m:item name=''随机模板防采集'' link=''rnd_templets_main.php'' rank=''plus_随机模板防采集'' target=''main'' />', '织梦团队', 1, 'rnd_templets_main.php');
INSERT INTO `#@__plus` VALUES (10, '木马扫描检测', '<m:item name=''木马扫描检测'' link=''virus_search.php'' rank=''plus_木马扫描检测'' target=''main'' />', '织梦团队', 1, 'virus_search.php');
INSERT INTO `#@__plus` VALUES (11, '数据转换与导入', '<m:item name=''数据转换与导入'' link=''member_data.php'' rank=''plus_数据转换与导入'' target=''main'' />', '织梦团队', 1, 'member_data.php,templets/member_data.htm');
INSERT INTO `#@__plus` VALUES (12, '百度新闻', '<m:item name=''百度新闻'' link=''baidunews.php'' rank=''plus_百度新闻'' target=''main'' />', '织梦团队', 1, 'baidunew.php,baidunew.htm');  
INSERT INTO `#@__plus` VALUES (13,'互动模块JS调用', '<m:item name=''互动模块JS调用'' link=''plus_js.php'' rank=''plus_互动模块JS调用'' target=''main'' />', '织梦团队', 1, 'plus_js.php');


INSERT INTO `#@__scores` VALUES (1, '列兵', 1, 10, 1);
INSERT INTO `#@__scores` VALUES (2, '少尉', 2, 500, 0);
INSERT INTO `#@__scores` VALUES (3, '中尉', 3, 900, 0);
INSERT INTO `#@__scores` VALUES (4, '上尉', 4, 1400, 0);
INSERT INTO `#@__scores` VALUES (6, '少校', 5, 2000, 0);


INSERT INTO `#@__softconfig` VALUES (0, 0, 0, 1, '');

INSERT INTO `#@__sysconfig` VALUES (9, 'cfg_backup_dir', '数据备份目录（在管理目录内）', 'backup_data', 'string', 5);
INSERT INTO `#@__sysconfig` VALUES (4, 'cfg_indexname', '主页链接名', '主页', 'string', 8);
INSERT INTO `#@__sysconfig` VALUES (9, 'cfg_html_editor', 'Html编辑器选项（仅支持 dede 和 fck）', 'fck', 'string', 5);
INSERT INTO `#@__sysconfig` VALUES (13, 'cfg_arcdir', '文档HTML默认保存路径', '/html', 'string', 8);
INSERT INTO `#@__sysconfig` VALUES (11, 'cfg_medias_dir', '图片/上传文件默认路径', '/uploads', 'string', 2);
INSERT INTO `#@__sysconfig` VALUES (12, 'cfg_ddimg_width', '缩略图默认宽度', '280', 'string', 2);
INSERT INTO `#@__sysconfig` VALUES (13, 'cfg_ddimg_height', '缩略图默认高度', '220', 'string', 2);
INSERT INTO `#@__sysconfig` VALUES (14, 'cfg_album_width', '图集默认显示图片的大小', '800', 'string', 2);
INSERT INTO `#@__sysconfig` VALUES (15, 'cfg_imgtype', '图片浏览器文件类型', 'jpg|gif|png', 'string', 2);
INSERT INTO `#@__sysconfig` VALUES (16, 'cfg_softtype', '附件浏览器文件类型', 'exe|zip|gz|rar|iso|doc|xsl|ppt|wps', 'string', 2);
INSERT INTO `#@__sysconfig` VALUES (17, 'cfg_mediatype', '多媒体浏览器文件类型', 'swf|mpg|dat|avi|mp3|rm|rmvb|wmv|asf|vob|wma|wav|mid|mov', 'string', 2);
INSERT INTO `#@__sysconfig` VALUES (9, 'cfg_specnote', '专题的最大节点数', '6', 'string', 5);
INSERT INTO `#@__sysconfig` VALUES (12, 'cfg_list_symbol', '栏目位置的间隔符号', '>', 'string', 8);
INSERT INTO `#@__sysconfig` VALUES (20, 'cfg_notallowstr', '禁用词语（系统将直接停止用户动作）', '#没设定#', 'string', 4);
INSERT INTO `#@__sysconfig` VALUES (21, 'cfg_feedbackcheck', '评论及留言(是/否)需审核', 'Y', 'bool', 4);
INSERT INTO `#@__sysconfig` VALUES (22, 'cfg_keyword_replace', '关键字替换(是/否)<br />&nbsp;&nbsp;使用本功能会影响HTML生成速度', 'Y', 'bool', 4);
INSERT INTO `#@__sysconfig` VALUES (5, 'cfg_fck_xhtml', '编辑器(是/否)使用XHTML', 'N', 'bool', 5);
INSERT INTO `#@__sysconfig` VALUES (11, 'cfg_df_style', '模板默认风格', 'default', 'string', 8);
INSERT INTO `#@__sysconfig` VALUES (25, 'cfg_multi_site', '是/否支持多站点\r\n  <br/>开启此项后附件、栏目连接、arclist内容启用绝对网址', 'N', 'bool', 8);
INSERT INTO `#@__sysconfig` VALUES (1, 'cfg_dede_cache', '是/否开启Dede模块引擎的缓存功能', 'Y', 'bool', 1);
INSERT INTO `#@__sysconfig` VALUES (1, 'cfg_dede_log', '是/否开启管理日志', 'N', 'bool', 5);
INSERT INTO `#@__sysconfig` VALUES (7, 'cfg_powerby', '网站版权信息', '网站版权信息', 'string', 8);
INSERT INTO `#@__sysconfig` VALUES (709, 'cfg_safeurl', '安全的引用地址(外部JS调用时可用到,多个用回车区别)', 'dedecms.com\r\nmysite.com\r\n', 'string', 4);
INSERT INTO `#@__sysconfig` VALUES (5, 'cfg_keywords', 'Meta 关键词', '织梦内容管理系统', 'string', 8);
INSERT INTO `#@__sysconfig` VALUES (5, 'cfg_arcsptitle', '(是/否)开启分页标题，开启会影响HTML生成速度', 'N', 'bool', 1);
INSERT INTO `#@__sysconfig` VALUES (6, 'cfg_arcautosp', '(是/否)开启长文章自动分页', 'N', 'bool', 1);
INSERT INTO `#@__sysconfig` VALUES (7, 'cfg_arcautosp_size', '文章自动分页大小（单位: K）', '5', 'string', 1);
INSERT INTO `#@__sysconfig` VALUES (6, 'cfg_auot_description', '自动摘要长度（0-250，0表示不启用）', '255', 'string', 5);
INSERT INTO `#@__sysconfig` VALUES (3, 'cfg_ftp_host', 'FTP主机', '', 'string', 9);
INSERT INTO `#@__sysconfig` VALUES (4, 'cfg_ftp_port', 'FTP端口', '21', 'string', 9);
INSERT INTO `#@__sysconfig` VALUES (5, 'cfg_ftp_user', 'FTP用户名', '', 'string', 9);
INSERT INTO `#@__sysconfig` VALUES (6, 'cfg_ftp_pwd', 'FTP密码', '', 'string', 9);
INSERT INTO `#@__sysconfig` VALUES (2, 'cfg_ftp_root', '网站根在FTP中的目录', '/', 'string', 9);
INSERT INTO `#@__sysconfig` VALUES (1, 'cfg_ftp_mkdir', '是否强制用FTP创建目录', 'N', 'bool', 9);
INSERT INTO `#@__sysconfig` VALUES (39, 'cfg_feedback_ck', '评论加验证码重确认', 'N', 'bool', 4);
INSERT INTO `#@__sysconfig` VALUES (0, 'cfg_list_son', '上级列表是否包含子类内容', 'Y', 'bool', 1);
INSERT INTO `#@__sysconfig` VALUES (1, 'cfg_mb_open', '是否开启会员功能', 'Y', 'bool', 3);
INSERT INTO `#@__sysconfig` VALUES (12, 'cfg_mb_album', '是否开启会员图集功能', 'Y', 'bool', 3);
INSERT INTO `#@__sysconfig` VALUES (10, 'cfg_mb_upload', '是否允许会员上传非图片附件', 'Y', 'bool', 3);
INSERT INTO `#@__sysconfig` VALUES (9, 'cfg_mb_upload_size', '会员上传文件大小(K)', '1024', 'string', 3);
INSERT INTO `#@__sysconfig` VALUES (6, 'cfg_mb_sendall', '是否开放会员对自定义模型投稿', 'Y', 'bool', 3);
INSERT INTO `#@__sysconfig` VALUES (11, 'cfg_mb_rmdown', '是否把会员指定的远程文档下载到本地', 'Y', 'bool', 3);
INSERT INTO `#@__sysconfig` VALUES (47, 'cfg_cli_time', '时区设置(默认+8)', '+8', 'string', 8);
INSERT INTO `#@__sysconfig` VALUES (8, 'cfg_mb_mediatype', '会员附件许可的类型', 'jpg|gif|png|bmp|swf|mp3|rmvb|wma|zip|rar|', 'string', 3);
INSERT INTO `#@__sysconfig` VALUES (8, 'cfg_mb_max', '会员附件总大小限制(MB)', '10', 'string', 3);
INSERT INTO `#@__sysconfig` VALUES (20, 'cfg_replacestr', '替换词语（词语会被替换成***）', '她妈|它妈|他妈|你妈|fuck|去死|贱人|老母', 'string', 4);
INSERT INTO `#@__sysconfig` VALUES (10, 'cfg_makeindex', '发布文档后自动更新网站主页', 'Y', 'bool', 1);
INSERT INTO `#@__sysconfig` VALUES (8, 'cfg_keyword_like', '使用关键词关连文章', 'Y', 'bool', 1);
INSERT INTO `#@__sysconfig` VALUES (14, 'cfg_online_type', '在线支付网关类型', 'nps', 'string', 1);
INSERT INTO `#@__sysconfig` VALUES (53, 'cfg_jpeg_query', 'JPEG缩略图质量', '100', 'string', 2);
INSERT INTO `#@__sysconfig` VALUES (3, 'cfg_pwdtype', '会员密码类型:none/md5/dd(织梦加密)', 'md5', 'string', 3);
INSERT INTO `#@__sysconfig` VALUES (4, 'cfg_md5len', 'MD5密码位数', '32', 'string', 3);
INSERT INTO `#@__sysconfig` VALUES (5, 'cfg_ddsign', '织梦加密算法密码(6-12位)\r\n<br />\r\n会员密码类型为dd时输入', '', 'string', 3);
INSERT INTO `#@__sysconfig` VALUES (58, 'cfg_use_vdcode', '是否开启后台登录的验证码', 'N', 'bool', 8);
INSERT INTO `#@__sysconfig` VALUES (7, 'cfg_send_score', '会员投稿增加积分', '2', 'string', 3);
INSERT INTO `#@__sysconfig` VALUES (7, 'cfg_guest_send', '是否允许游客投稿', 'N', 'bool', 3);
INSERT INTO `#@__sysconfig` VALUES (2, 'cfg_al_cachetime', 'arclist标记缓存时间(小时)', '1', 'string', 1);
INSERT INTO `#@__sysconfig` VALUES (6, 'cfg_df_score', '注册会员默认积分', '1000', 'string', 3);
INSERT INTO `#@__sysconfig` VALUES (2, 'cfg_member_regsta', '新注册会员是否需要审核', 'N', 'bool', 3);
INSERT INTO `#@__sysconfig` VALUES (9, 'cfg_up_prenext', '更新单个文档时是否同时更新上一篇和下一篇', 'N', 'bool', 1);
INSERT INTO `#@__sysconfig` VALUES (18, 'cfg_mb_exiturl', '会员退出后默认跳转页', '/', 'string', 3);
INSERT INTO `#@__sysconfig` VALUES (8, 'cfg_ct_mode', '内容管理模式(0-传统，1-分表)', '1', 'string', 5);
INSERT INTO `#@__sysconfig` VALUES (15, 'cfg_mb_score2money', '是否开启积分和金币兑换功能', 'Y', 'bool', 3);
INSERT INTO `#@__sysconfig` VALUES (16, 'cfg_score2money', '多少积分兑换一个金币', '3', 'string', 3);
INSERT INTO `#@__sysconfig` VALUES (17, 'cfg_money2score', '一个金币购买多少积分', '3', 'string', 3);
INSERT INTO `#@__sysconfig` VALUES (0, 'cfg_websafe_open', '关闭站点(仅允许访问后台及前台部份程序)', 'N', 'bool', 8);
INSERT INTO `#@__sysconfig` VALUES (7, 'cfg_cat_seltype', '栏目选择类型(0-弹窗、1-select列表)', '1', 'string', 5);
INSERT INTO `#@__sysconfig` VALUES (3, 'cfg_arc_all', '是否在arclist标记中包含附加表指定的字段', 'N', 'bool', 1);
INSERT INTO `#@__sysconfig` VALUES (101, 'cfg_gif_wartermark', 'gif图片是否增加水印', 'N', 'bool', 2);
INSERT INTO `#@__sysconfig` VALUES (11, 'cfg_allsearch_limit', '网站全局搜索时间限制', '1', 'string', 1);
INSERT INTO `#@__sysconfig` VALUES (12, 'cfg_search_maxlimit', '搜索结果最大数限制', '500', 'string', 1);
INSERT INTO `#@__sysconfig` VALUES (13, 'cfg_search_cachetime', '搜索缓存有效期（单位：小时）', '1', 'string', 1);
INSERT INTO `#@__sysconfig` VALUES (14, 'cfg_locked_day', '会员文章加锁时间(天)审核后多少天不能再修改', '7', 'string', 3);
INSERT INTO `#@__sysconfig` VALUES (107, 'cfg_sendmail_bysmtp', '是否启用smtp方式发送邮件', 'Y', 'bool', 10);
INSERT INTO `#@__sysconfig` VALUES (108, 'cfg_smtp_server', 'smtp服务器', 'smtp.xinhuanet.com', 'string', 10);
INSERT INTO `#@__sysconfig` VALUES (109, 'cfg_smtp_port', 'smtp服务器端口', '25', 'string', 10);
INSERT INTO `#@__sysconfig` VALUES (110, 'cfg_smtp_usermail', 'SMTP服务器的用户邮箱', '', 'string', 10);
INSERT INTO `#@__sysconfig` VALUES (111, 'cfg_smtp_user', 'SMTP服务器的用户帐号', '', 'string', 10);
INSERT INTO `#@__sysconfig` VALUES (112, 'cfg_smtp_password', 'SMTP服务器的用户密码', '', 'string', 10);
INSERT INTO `#@__sysconfig` VALUES (114, 'cfg_feedback_make', '评论后是否更新文档', 'Y', 'bool', 4);
INSERT INTO `#@__sysconfig` VALUES (200, 'cfg_ask', '是否启用问答模块', 'Y', 'bool', 6);
INSERT INTO `#@__sysconfig` VALUES (201, 'cfg_ask_ifcheck', '问答模块提问是否需要审核', 'N', 'bool', 6);
INSERT INTO `#@__sysconfig` VALUES (202, 'cfg_ask_dateformat', '问答模块日期格式', 'Y-n-j', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (203, 'cfg_ask_timeformat', '问答模块时间格式', 'H:i', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (204, 'cfg_ask_timeoffset', '问答模块时区设定', '8', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (205, 'cfg_ask_gzipcompress', '是否启用gzip压缩', '1', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (206, 'cfg_ask_authkey', '问答模块会员key', 'AeN896fG', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (207, 'cfg_ask_cookiepre', '问答模块cookie前缀', 'deask_', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (208, 'cfg_answer_ifcheck', '问答模块回答问题是否需要审核', 'N', 'bool', 6);
INSERT INTO `#@__sysconfig` VALUES (209, 'cfg_ask_expiredtime', '问答模块问题有效期（天）', '20', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (210, 'cfg_ask_tpp', '问答模块列表显示问题数', '14', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (211, 'cfg_ask_sitename', '问答系统名称', '织梦问答', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (212, 'cfg_ask_symbols', '问答模块导航间隔符', '>', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (213, 'cfg_ask_answerscore', ' 会员回答问题就增加积分', '2', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (214, 'cfg_ask_bestanswer', '最佳答案系统奖励积分', '20', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (215, 'cfg_ask_subtypenum', '首页显示子类数据', '10', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (301, 'cfg_group_creators', '圈子模块,要达多该积分数才可以创建圈子', '1000', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (302, 'cfg_group_max', '用户最多可圈子数量,0不限制.', '0', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (303, 'cfg_group_maxuser', '圈子可接受用户数量,0不限制', '0', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (304, 'cfg_group_click', '加入圈子用户是否审核,0 不,1 要', '1', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (305, 'cfg_group_words', '圈子一贴子可发字符数', '1000', 'string', 6);
INSERT INTO `#@__sysconfig` VALUES (701, 'cfg_book_freenum', '连载内容默认免费章节(-1为全开放)', '6', 'string', 7);
INSERT INTO `#@__sysconfig` VALUES (702, 'cfg_book_pay', '收费图书计费形式(1按图书，2按章节)', '1', 'string', 7);
INSERT INTO `#@__sysconfig` VALUES (703, 'cfg_book_money', '收费图书花费金币数', '1', 'string', 7);
INSERT INTO `#@__sysconfig` VALUES (704, 'cfg_book_freerank', '免费阅读所有内容会员级别值', '100', 'string', 7);
INSERT INTO `#@__sysconfig` VALUES (13, 'cfg_book_ifcheck', '会员发布图书是否需要审核', 'Y', 'bool', 3);
INSERT INTO `#@__sysconfig` VALUES (92, 'cfg_siteid', 'PW营销系统密钥一', '', 'string', 5);
INSERT INTO `#@__sysconfig` VALUES (93, 'cfg_siteownerid', 'PW营销系统密钥二', '', 'string', 5);
INSERT INTO `#@__sysconfig` VALUES (91, 'cfg_sitehash', 'PW营销唯一识别码', '', 'string', 5);
INSERT INTO `#@__sysconfig` VALUES (6, 'cfg_description', 'Meta 描述', '织梦内容管理系统是不错的系统', 'string', 8);
INSERT INTO `#@__sysconfig` VALUES (9, 'cfg_beian', '备案号', '', 'string', 8);
INSERT INTO `#@__sysconfig` VALUES (10, 'cfg_updateperi', '百度新闻xml更新时间 （单位：分钟）', '15', 'string', 5);
INSERT INTO `#@__sysconfig` VALUES (11, 'cfg_baidunews_limit', '百度新闻xml更新新闻数量 最大100', '100', 'string', 5);

INSERT INTO `#@__syspassport` VALUES ('0', 'cfg_pp_isopen');
INSERT INTO `#@__syspassport` VALUES ('', 'cfg_pp_loginurl');
INSERT INTO `#@__syspassport` VALUES ('论坛', 'cfg_pp_name');

INSERT INTO `#@__vote` VALUES (1, '你是从哪儿得知本站的？', 1163894400, 1268956800, 711, 0, '<v:note id=''1'' count=''350''>朋友介绍</v:note>\r\n<v:note id=''2'' count=''45''>门户网站的搜索引擎</v:note>\r\n<v:note id=''3'' count=''118''>Google或百度搜索</v:note>\r\n<v:note id=''4'' count=''119''>别的网站上的链接</v:note>\r\n<v:note id=''5'' count=''79''>其它途径</v:note>\r\n');


INSERT INTO `dede_area` VALUES (1, '北京市', 0, 0);
INSERT INTO `dede_area` VALUES (102, '西城区', 1, 2);
INSERT INTO `dede_area` VALUES (3116, '崇文区', 1, 0);
INSERT INTO `dede_area` VALUES (104, '宣武区', 1, 0);
INSERT INTO `dede_area` VALUES (105, '朝阳区', 1, 0);
INSERT INTO `dede_area` VALUES (106, '海淀区', 1, 0);
INSERT INTO `dede_area` VALUES (107, '丰台区', 1, 0);
INSERT INTO `dede_area` VALUES (108, '石景山区', 1, 0);
INSERT INTO `dede_area` VALUES (109, '门头沟区', 1, 0);
INSERT INTO `dede_area` VALUES (110, '房山区', 1, 0);
INSERT INTO `dede_area` VALUES (111, '通州区', 1, 0);
INSERT INTO `dede_area` VALUES (112, '顺义区', 1, 0);
INSERT INTO `dede_area` VALUES (113, '昌平区', 1, 0);
INSERT INTO `dede_area` VALUES (114, '大兴区', 1, 0);
INSERT INTO `dede_area` VALUES (115, '平谷县', 1, 0);
INSERT INTO `dede_area` VALUES (116, '怀柔县', 1, 0);
INSERT INTO `dede_area` VALUES (117, '密云县', 1, 0);
INSERT INTO `dede_area` VALUES (118, '延庆县', 1, 0);
INSERT INTO `dede_area` VALUES (2, '上海市', 0, 0);
INSERT INTO `dede_area` VALUES (201, '黄浦区', 2, 0);
INSERT INTO `dede_area` VALUES (202, '卢湾区', 2, 0);
INSERT INTO `dede_area` VALUES (203, '徐汇区', 2, 0);
INSERT INTO `dede_area` VALUES (204, '长宁区', 2, 0);
INSERT INTO `dede_area` VALUES (205, '静安区', 2, 0);
INSERT INTO `dede_area` VALUES (206, '普陀区', 2, 0);
INSERT INTO `dede_area` VALUES (207, '闸北区', 2, 0);
INSERT INTO `dede_area` VALUES (208, '虹口区', 2, 0);
INSERT INTO `dede_area` VALUES (209, '杨浦区', 2, 0);
INSERT INTO `dede_area` VALUES (210, '宝山区', 2, 0);
INSERT INTO `dede_area` VALUES (211, '闵行区', 2, 0);
INSERT INTO `dede_area` VALUES (212, '嘉定区', 2, 0);
INSERT INTO `dede_area` VALUES (213, '浦东新区', 2, 0);
INSERT INTO `dede_area` VALUES (214, '松江区', 2, 0);
INSERT INTO `dede_area` VALUES (215, '金山区', 2, 0);
INSERT INTO `dede_area` VALUES (216, '青浦区', 2, 0);
INSERT INTO `dede_area` VALUES (217, '南汇区', 2, 0);
INSERT INTO `dede_area` VALUES (218, '奉贤区', 2, 0);
INSERT INTO `dede_area` VALUES (219, '崇明县', 2, 0);
INSERT INTO `dede_area` VALUES (3, '天津市', 0, 0);
INSERT INTO `dede_area` VALUES (301, '和平区', 3, 0);
INSERT INTO `dede_area` VALUES (302, '河东区', 3, 0);
INSERT INTO `dede_area` VALUES (303, '河西区', 3, 0);
INSERT INTO `dede_area` VALUES (304, '南开区', 3, 0);
INSERT INTO `dede_area` VALUES (305, '河北区', 3, 0);
INSERT INTO `dede_area` VALUES (306, '红桥区', 3, 0);
INSERT INTO `dede_area` VALUES (307, '塘沽区', 3, 0);
INSERT INTO `dede_area` VALUES (308, '汉沽区', 3, 0);
INSERT INTO `dede_area` VALUES (309, '大港区', 3, 0);
INSERT INTO `dede_area` VALUES (310, '东丽区', 3, 0);
INSERT INTO `dede_area` VALUES (311, '西青区', 3, 0);
INSERT INTO `dede_area` VALUES (312, '北辰区', 3, 0);
INSERT INTO `dede_area` VALUES (313, '津南区', 3, 0);
INSERT INTO `dede_area` VALUES (314, '武清区', 3, 0);
INSERT INTO `dede_area` VALUES (315, '宝坻区', 3, 0);
INSERT INTO `dede_area` VALUES (316, '静海县', 3, 0);
INSERT INTO `dede_area` VALUES (317, '宁河县', 3, 0);
INSERT INTO `dede_area` VALUES (318, '蓟县', 3, 0);
INSERT INTO `dede_area` VALUES (4, '重庆市', 0, 0);
INSERT INTO `dede_area` VALUES (401, '渝中区', 4, 0);
INSERT INTO `dede_area` VALUES (402, '大渡口区', 4, 0);
INSERT INTO `dede_area` VALUES (403, '江北区', 4, 0);
INSERT INTO `dede_area` VALUES (404, '沙坪坝区', 4, 0);
INSERT INTO `dede_area` VALUES (405, '九龙坡区', 4, 0);
INSERT INTO `dede_area` VALUES (406, '南岸区', 4, 0);
INSERT INTO `dede_area` VALUES (407, '北碚区', 4, 0);
INSERT INTO `dede_area` VALUES (408, '万盛区', 4, 0);
INSERT INTO `dede_area` VALUES (409, '双桥区', 4, 0);
INSERT INTO `dede_area` VALUES (410, '渝北区', 4, 0);
INSERT INTO `dede_area` VALUES (411, '巴南区', 4, 0);
INSERT INTO `dede_area` VALUES (412, '万州区', 4, 0);
INSERT INTO `dede_area` VALUES (413, '涪陵区', 4, 0);
INSERT INTO `dede_area` VALUES (414, '黔江区', 4, 0);
INSERT INTO `dede_area` VALUES (415, '永川市', 4, 0);
INSERT INTO `dede_area` VALUES (416, '合川市', 4, 0);
INSERT INTO `dede_area` VALUES (417, '江津市', 4, 0);
INSERT INTO `dede_area` VALUES (418, '南川市', 4, 0);
INSERT INTO `dede_area` VALUES (419, '长寿县', 4, 0);
INSERT INTO `dede_area` VALUES (420, '綦江县', 4, 0);
INSERT INTO `dede_area` VALUES (421, '潼南县', 4, 0);
INSERT INTO `dede_area` VALUES (422, '荣昌县', 4, 0);
INSERT INTO `dede_area` VALUES (423, '璧山县', 4, 0);
INSERT INTO `dede_area` VALUES (424, '大足县', 4, 0);
INSERT INTO `dede_area` VALUES (425, '铜梁县', 4, 0);
INSERT INTO `dede_area` VALUES (426, '梁平县', 4, 0);
INSERT INTO `dede_area` VALUES (427, '城口县', 4, 0);
INSERT INTO `dede_area` VALUES (428, '垫江县', 4, 0);
INSERT INTO `dede_area` VALUES (429, '武隆县', 4, 0);
INSERT INTO `dede_area` VALUES (430, '丰都县', 4, 0);
INSERT INTO `dede_area` VALUES (431, '奉节县', 4, 0);
INSERT INTO `dede_area` VALUES (432, '开县', 4, 0);
INSERT INTO `dede_area` VALUES (433, '云阳县', 4, 0);
INSERT INTO `dede_area` VALUES (434, '忠县', 4, 0);
INSERT INTO `dede_area` VALUES (435, '巫溪县', 4, 0);
INSERT INTO `dede_area` VALUES (436, '巫山县', 4, 0);
INSERT INTO `dede_area` VALUES (437, '石柱县', 4, 0);
INSERT INTO `dede_area` VALUES (438, '秀山县', 4, 0);
INSERT INTO `dede_area` VALUES (439, '酉阳县', 4, 0);
INSERT INTO `dede_area` VALUES (440, '彭水县', 4, 0);
INSERT INTO `dede_area` VALUES (5, '广东省', 0, 0);
INSERT INTO `dede_area` VALUES (501, '广州市', 5, 0);
INSERT INTO `dede_area` VALUES (502, '深圳市', 5, 0);
INSERT INTO `dede_area` VALUES (503, '珠海市', 5, 0);
INSERT INTO `dede_area` VALUES (504, '汕头市', 5, 0);
INSERT INTO `dede_area` VALUES (505, '韶关市', 5, 0);
INSERT INTO `dede_area` VALUES (506, '河源市', 5, 0);
INSERT INTO `dede_area` VALUES (507, '梅州市', 5, 0);
INSERT INTO `dede_area` VALUES (508, '惠州市', 5, 0);
INSERT INTO `dede_area` VALUES (509, '汕尾市', 5, 0);
INSERT INTO `dede_area` VALUES (510, '东莞市', 5, 0);
INSERT INTO `dede_area` VALUES (511, '中山市', 5, 0);
INSERT INTO `dede_area` VALUES (512, '江门市', 5, 0);
INSERT INTO `dede_area` VALUES (513, '佛山市', 5, 0);
INSERT INTO `dede_area` VALUES (514, '阳江市', 5, 0);
INSERT INTO `dede_area` VALUES (515, '湛江市', 5, 0);
INSERT INTO `dede_area` VALUES (516, '茂名市', 5, 0);
INSERT INTO `dede_area` VALUES (517, '肇庆市', 5, 0);
INSERT INTO `dede_area` VALUES (518, '清远市', 5, 0);
INSERT INTO `dede_area` VALUES (519, '潮州市', 5, 0);
INSERT INTO `dede_area` VALUES (520, '揭阳市', 5, 0);
INSERT INTO `dede_area` VALUES (521, '云浮市', 5, 0);
INSERT INTO `dede_area` VALUES (6, '福建省', 0, 0);
INSERT INTO `dede_area` VALUES (601, '福州市', 6, 0);
INSERT INTO `dede_area` VALUES (602, '厦门市', 6, 0);
INSERT INTO `dede_area` VALUES (603, '三明市', 6, 0);
INSERT INTO `dede_area` VALUES (604, '莆田市', 6, 0);
INSERT INTO `dede_area` VALUES (605, '泉州市', 6, 0);
INSERT INTO `dede_area` VALUES (606, '漳州市', 6, 0);
INSERT INTO `dede_area` VALUES (607, '南平市', 6, 0);
INSERT INTO `dede_area` VALUES (608, '龙岩市', 6, 0);
INSERT INTO `dede_area` VALUES (609, '宁德市', 6, 0);
INSERT INTO `dede_area` VALUES (7, '浙江省', 0, 0);
INSERT INTO `dede_area` VALUES (701, '杭州市', 7, 0);
INSERT INTO `dede_area` VALUES (702, '宁波市', 7, 0);
INSERT INTO `dede_area` VALUES (703, '温州市', 7, 0);
INSERT INTO `dede_area` VALUES (704, '嘉兴市', 7, 0);
INSERT INTO `dede_area` VALUES (705, '湖州市', 7, 0);
INSERT INTO `dede_area` VALUES (706, '绍兴市', 7, 0);
INSERT INTO `dede_area` VALUES (707, '金华市', 7, 0);
INSERT INTO `dede_area` VALUES (708, '衢州市', 7, 0);
INSERT INTO `dede_area` VALUES (709, '舟山市', 7, 0);
INSERT INTO `dede_area` VALUES (710, '台州市', 7, 0);
INSERT INTO `dede_area` VALUES (711, '丽水市', 7, 0);
INSERT INTO `dede_area` VALUES (8, '江苏省', 0, 0);
INSERT INTO `dede_area` VALUES (801, '南京市', 8, 0);
INSERT INTO `dede_area` VALUES (802, '徐州市', 8, 0);
INSERT INTO `dede_area` VALUES (803, '连云港市', 8, 0);
INSERT INTO `dede_area` VALUES (804, '淮安市', 8, 0);
INSERT INTO `dede_area` VALUES (805, '宿迁市', 8, 0);
INSERT INTO `dede_area` VALUES (806, '盐城市', 8, 0);
INSERT INTO `dede_area` VALUES (807, '扬州市', 8, 0);
INSERT INTO `dede_area` VALUES (808, '泰州市', 8, 0);
INSERT INTO `dede_area` VALUES (809, '南通市', 8, 0);
INSERT INTO `dede_area` VALUES (810, '镇江市', 8, 0);
INSERT INTO `dede_area` VALUES (811, '常州市', 8, 0);
INSERT INTO `dede_area` VALUES (812, '无锡市', 8, 0);
INSERT INTO `dede_area` VALUES (813, '苏州市', 8, 0);
INSERT INTO `dede_area` VALUES (9, '山东省', 0, 0);
INSERT INTO `dede_area` VALUES (901, '济南市', 9, 0);
INSERT INTO `dede_area` VALUES (902, '青岛市', 9, 0);
INSERT INTO `dede_area` VALUES (903, '淄博市', 9, 0);
INSERT INTO `dede_area` VALUES (904, '枣庄市', 9, 0);
INSERT INTO `dede_area` VALUES (905, '东营市', 9, 0);
INSERT INTO `dede_area` VALUES (906, '潍坊市', 9, 0);
INSERT INTO `dede_area` VALUES (907, '烟台市', 9, 0);
INSERT INTO `dede_area` VALUES (908, '威海市', 9, 0);
INSERT INTO `dede_area` VALUES (909, '济宁市', 9, 0);
INSERT INTO `dede_area` VALUES (910, '泰安市', 9, 0);
INSERT INTO `dede_area` VALUES (911, '日照市', 9, 0);
INSERT INTO `dede_area` VALUES (912, '莱芜市', 9, 0);
INSERT INTO `dede_area` VALUES (913, '德州市', 9, 0);
INSERT INTO `dede_area` VALUES (914, '临沂市', 9, 0);
INSERT INTO `dede_area` VALUES (915, '聊城市', 9, 0);
INSERT INTO `dede_area` VALUES (916, '滨州市', 9, 0);
INSERT INTO `dede_area` VALUES (917, '菏泽市', 9, 0);
INSERT INTO `dede_area` VALUES (10, '辽宁省', 0, 0);
INSERT INTO `dede_area` VALUES (1001, '沈阳市', 10, 0);
INSERT INTO `dede_area` VALUES (1002, '大连市', 10, 0);
INSERT INTO `dede_area` VALUES (1003, '鞍山市', 10, 0);
INSERT INTO `dede_area` VALUES (1004, '抚顺市', 10, 0);
INSERT INTO `dede_area` VALUES (1005, '本溪市', 10, 0);
INSERT INTO `dede_area` VALUES (1006, '丹东市', 10, 0);
INSERT INTO `dede_area` VALUES (1007, '锦州市', 10, 0);
INSERT INTO `dede_area` VALUES (1008, '葫芦岛市', 10, 0);
INSERT INTO `dede_area` VALUES (1009, '营口市', 10, 0);
INSERT INTO `dede_area` VALUES (1010, '盘锦市', 10, 0);
INSERT INTO `dede_area` VALUES (1011, '阜新市', 10, 0);
INSERT INTO `dede_area` VALUES (1012, '辽阳市', 10, 0);
INSERT INTO `dede_area` VALUES (1013, '铁岭市', 10, 0);
INSERT INTO `dede_area` VALUES (1014, '朝阳市', 10, 0);
INSERT INTO `dede_area` VALUES (11, '江西省', 0, 0);
INSERT INTO `dede_area` VALUES (1101, '南昌市', 11, 0);
INSERT INTO `dede_area` VALUES (1102, '景德镇市', 11, 0);
INSERT INTO `dede_area` VALUES (1103, '萍乡市', 11, 0);
INSERT INTO `dede_area` VALUES (1104, '新余市', 11, 0);
INSERT INTO `dede_area` VALUES (1105, '九江市', 11, 0);
INSERT INTO `dede_area` VALUES (1106, '鹰潭市', 11, 0);
INSERT INTO `dede_area` VALUES (1107, '赣州市', 11, 0);
INSERT INTO `dede_area` VALUES (1108, '吉安市', 11, 0);
INSERT INTO `dede_area` VALUES (1109, '宜春市', 11, 0);
INSERT INTO `dede_area` VALUES (1110, '抚州市', 11, 0);
INSERT INTO `dede_area` VALUES (1111, '上饶市', 11, 0);
INSERT INTO `dede_area` VALUES (12, '四川省', 0, 0);
INSERT INTO `dede_area` VALUES (1201, '成都市', 12, 0);
INSERT INTO `dede_area` VALUES (1202, '自贡市', 12, 0);
INSERT INTO `dede_area` VALUES (1203, '攀枝花市', 12, 0);
INSERT INTO `dede_area` VALUES (1204, '泸州市', 12, 0);
INSERT INTO `dede_area` VALUES (1205, '德阳市', 12, 0);
INSERT INTO `dede_area` VALUES (1206, '绵阳市', 12, 0);
INSERT INTO `dede_area` VALUES (1207, '广元市', 12, 0);
INSERT INTO `dede_area` VALUES (1208, '遂宁市', 12, 0);
INSERT INTO `dede_area` VALUES (1209, '内江市', 12, 0);
INSERT INTO `dede_area` VALUES (1210, '乐山市', 12, 0);
INSERT INTO `dede_area` VALUES (1211, '南充市', 12, 0);
INSERT INTO `dede_area` VALUES (1212, '宜宾市', 12, 0);
INSERT INTO `dede_area` VALUES (1213, '广安市', 12, 0);
INSERT INTO `dede_area` VALUES (1214, '达州市', 12, 0);
INSERT INTO `dede_area` VALUES (1215, '巴中市', 12, 0);
INSERT INTO `dede_area` VALUES (1216, '雅安市', 12, 0);
INSERT INTO `dede_area` VALUES (1217, '眉山市', 12, 0);
INSERT INTO `dede_area` VALUES (1218, '资阳市', 12, 0);
INSERT INTO `dede_area` VALUES (1219, '阿坝州', 12, 0);
INSERT INTO `dede_area` VALUES (1220, '甘孜州', 12, 0);
INSERT INTO `dede_area` VALUES (1221, '凉山州', 12, 0);
INSERT INTO `dede_area` VALUES (13, '陕西省', 0, 0);
INSERT INTO `dede_area` VALUES (3114, '西安市', 13, 0);
INSERT INTO `dede_area` VALUES (1302, '铜川市', 13, 0);
INSERT INTO `dede_area` VALUES (1303, '宝鸡市', 13, 0);
INSERT INTO `dede_area` VALUES (1304, '咸阳市', 13, 0);
INSERT INTO `dede_area` VALUES (1305, '渭南市', 13, 0);
INSERT INTO `dede_area` VALUES (1306, '延安市', 13, 0);
INSERT INTO `dede_area` VALUES (1307, '汉中市', 13, 0);
INSERT INTO `dede_area` VALUES (1308, '榆林市', 13, 0);
INSERT INTO `dede_area` VALUES (1309, '安康市', 13, 0);
INSERT INTO `dede_area` VALUES (1310, '商洛地区', 13, 0);
INSERT INTO `dede_area` VALUES (14, '湖北省', 0, 0);
INSERT INTO `dede_area` VALUES (1401, '武汉市', 14, 0);
INSERT INTO `dede_area` VALUES (1402, '黄石市', 14, 0);
INSERT INTO `dede_area` VALUES (1403, '襄樊市', 14, 0);
INSERT INTO `dede_area` VALUES (1404, '十堰市', 14, 0);
INSERT INTO `dede_area` VALUES (1405, '荆州市', 14, 0);
INSERT INTO `dede_area` VALUES (1406, '宜昌市', 14, 0);
INSERT INTO `dede_area` VALUES (1407, '荆门市', 14, 0);
INSERT INTO `dede_area` VALUES (1408, '鄂州市', 14, 0);
INSERT INTO `dede_area` VALUES (1409, '孝感市', 14, 0);
INSERT INTO `dede_area` VALUES (1410, '黄冈市', 14, 0);
INSERT INTO `dede_area` VALUES (1411, '咸宁市', 14, 0);
INSERT INTO `dede_area` VALUES (1412, '随州市', 14, 0);
INSERT INTO `dede_area` VALUES (1413, '仙桃市', 14, 0);
INSERT INTO `dede_area` VALUES (1414, '天门市', 14, 0);
INSERT INTO `dede_area` VALUES (1415, '潜江市', 14, 0);
INSERT INTO `dede_area` VALUES (1416, '神农架', 14, 0);
INSERT INTO `dede_area` VALUES (1417, '恩施州', 14, 0);
INSERT INTO `dede_area` VALUES (15, '河南省', 0, 0);
INSERT INTO `dede_area` VALUES (1501, '郑州市', 15, 0);
INSERT INTO `dede_area` VALUES (1502, '开封市', 15, 0);
INSERT INTO `dede_area` VALUES (1503, '洛阳市', 15, 0);
INSERT INTO `dede_area` VALUES (1504, '平顶山市', 15, 0);
INSERT INTO `dede_area` VALUES (1505, '焦作市', 15, 0);
INSERT INTO `dede_area` VALUES (1506, '鹤壁市', 15, 0);
INSERT INTO `dede_area` VALUES (1507, '新乡市', 15, 0);
INSERT INTO `dede_area` VALUES (1508, '安阳市', 15, 0);
INSERT INTO `dede_area` VALUES (1509, '濮阳市', 15, 0);
INSERT INTO `dede_area` VALUES (1510, '许昌市', 15, 0);
INSERT INTO `dede_area` VALUES (1511, '漯河市', 15, 0);
INSERT INTO `dede_area` VALUES (1512, '三门峡市', 15, 0);
INSERT INTO `dede_area` VALUES (1513, '南阳市', 15, 0);
INSERT INTO `dede_area` VALUES (1514, '商丘市', 15, 0);
INSERT INTO `dede_area` VALUES (1515, '信阳市', 15, 0);
INSERT INTO `dede_area` VALUES (1516, '周口市', 15, 0);
INSERT INTO `dede_area` VALUES (1517, '驻马店市', 15, 0);
INSERT INTO `dede_area` VALUES (1518, '济源市', 15, 0);
INSERT INTO `dede_area` VALUES (16, '河北省', 0, 0);
INSERT INTO `dede_area` VALUES (1601, '石家庄市', 16, 0);
INSERT INTO `dede_area` VALUES (1602, '唐山市', 16, 0);
INSERT INTO `dede_area` VALUES (1603, '秦皇岛市', 16, 0);
INSERT INTO `dede_area` VALUES (1604, '邯郸市', 16, 0);
INSERT INTO `dede_area` VALUES (1605, '邢台市', 16, 0);
INSERT INTO `dede_area` VALUES (1606, '保定市', 16, 0);
INSERT INTO `dede_area` VALUES (1607, '张家口市', 16, 0);
INSERT INTO `dede_area` VALUES (1608, '承德市', 16, 0);
INSERT INTO `dede_area` VALUES (1609, '沧州市', 16, 0);
INSERT INTO `dede_area` VALUES (1610, '廊坊市', 16, 0);
INSERT INTO `dede_area` VALUES (1611, '衡水市', 16, 0);
INSERT INTO `dede_area` VALUES (17, '山西省', 0, 0);
INSERT INTO `dede_area` VALUES (1701, '太原市', 17, 0);
INSERT INTO `dede_area` VALUES (1702, '大同市', 17, 0);
INSERT INTO `dede_area` VALUES (1703, '阳泉市', 17, 0);
INSERT INTO `dede_area` VALUES (1704, '长治市', 17, 0);
INSERT INTO `dede_area` VALUES (1705, '晋城市', 17, 0);
INSERT INTO `dede_area` VALUES (1706, '朔州市', 17, 0);
INSERT INTO `dede_area` VALUES (1707, '晋中市', 17, 0);
INSERT INTO `dede_area` VALUES (1708, '忻州市', 17, 0);
INSERT INTO `dede_area` VALUES (1709, '临汾市', 17, 0);
INSERT INTO `dede_area` VALUES (1710, '运城市', 17, 0);
INSERT INTO `dede_area` VALUES (1711, '吕梁地区', 17, 0);
INSERT INTO `dede_area` VALUES (18, '内蒙古', 0, 0);
INSERT INTO `dede_area` VALUES (1801, '呼和浩特', 18, 0);
INSERT INTO `dede_area` VALUES (1802, '包头市', 18, 0);
INSERT INTO `dede_area` VALUES (1803, '乌海市', 18, 0);
INSERT INTO `dede_area` VALUES (1804, '赤峰市', 18, 0);
INSERT INTO `dede_area` VALUES (1805, '通辽市', 18, 0);
INSERT INTO `dede_area` VALUES (1806, '鄂尔多斯', 18, 0);
INSERT INTO `dede_area` VALUES (1807, '乌兰察布', 18, 0);
INSERT INTO `dede_area` VALUES (1808, '锡林郭勒', 18, 0);
INSERT INTO `dede_area` VALUES (1809, '呼伦贝尔', 18, 0);
INSERT INTO `dede_area` VALUES (1810, '巴彦淖尔', 18, 0);
INSERT INTO `dede_area` VALUES (1811, '阿拉善盟', 18, 0);
INSERT INTO `dede_area` VALUES (1812, '兴安盟', 18, 0);
INSERT INTO `dede_area` VALUES (19, '吉林省', 0, 0);
INSERT INTO `dede_area` VALUES (1901, '长春市', 19, 0);
INSERT INTO `dede_area` VALUES (1902, '吉林市', 19, 0);
INSERT INTO `dede_area` VALUES (1903, '四平市', 19, 0);
INSERT INTO `dede_area` VALUES (1904, '辽源市', 19, 0);
INSERT INTO `dede_area` VALUES (1905, '通化市', 19, 0);
INSERT INTO `dede_area` VALUES (1906, '白山市', 19, 0);
INSERT INTO `dede_area` VALUES (1907, '松原市', 19, 0);
INSERT INTO `dede_area` VALUES (1908, '白城市', 19, 0);
INSERT INTO `dede_area` VALUES (1909, '延边州', 19, 0);
INSERT INTO `dede_area` VALUES (20, '黑龙江', 0, 0);
INSERT INTO `dede_area` VALUES (2001, '哈尔滨市', 20, 0);
INSERT INTO `dede_area` VALUES (2002, '齐齐哈尔', 20, 0);
INSERT INTO `dede_area` VALUES (2003, '鹤岗市', 20, 0);
INSERT INTO `dede_area` VALUES (2004, '双鸭山市', 20, 0);
INSERT INTO `dede_area` VALUES (2005, '鸡西市', 20, 0);
INSERT INTO `dede_area` VALUES (2006, '大庆市', 20, 0);
INSERT INTO `dede_area` VALUES (2007, '伊春市', 20, 0);
INSERT INTO `dede_area` VALUES (2008, '牡丹江市', 20, 0);
INSERT INTO `dede_area` VALUES (2009, '佳木斯市', 20, 0);
INSERT INTO `dede_area` VALUES (2010, '七台河市', 20, 0);
INSERT INTO `dede_area` VALUES (2011, '黑河市', 20, 0);
INSERT INTO `dede_area` VALUES (2012, '绥化市', 20, 0);
INSERT INTO `dede_area` VALUES (2013, '大兴安岭', 20, 0);
INSERT INTO `dede_area` VALUES (21, '安徽省', 0, 0);
INSERT INTO `dede_area` VALUES (2101, '合肥市', 21, 0);
INSERT INTO `dede_area` VALUES (2102, '芜湖市', 21, 0);
INSERT INTO `dede_area` VALUES (2103, '蚌埠市', 21, 0);
INSERT INTO `dede_area` VALUES (2104, '淮南市', 21, 0);
INSERT INTO `dede_area` VALUES (2105, '马鞍山市', 21, 0);
INSERT INTO `dede_area` VALUES (2106, '淮北市', 21, 0);
INSERT INTO `dede_area` VALUES (2107, '铜陵市', 21, 0);
INSERT INTO `dede_area` VALUES (2108, '安庆市', 21, 0);
INSERT INTO `dede_area` VALUES (2109, '黄山市', 21, 0);
INSERT INTO `dede_area` VALUES (2110, '滁州市', 21, 0);
INSERT INTO `dede_area` VALUES (2111, '阜阳市', 21, 0);
INSERT INTO `dede_area` VALUES (2112, '宿州市', 21, 0);
INSERT INTO `dede_area` VALUES (2113, '巢湖市', 21, 0);
INSERT INTO `dede_area` VALUES (2114, '六安市', 21, 0);
INSERT INTO `dede_area` VALUES (2115, '亳州市', 21, 0);
INSERT INTO `dede_area` VALUES (2116, '宣城市', 21, 0);
INSERT INTO `dede_area` VALUES (2117, '池州市', 21, 0);
INSERT INTO `dede_area` VALUES (22, '湖南省', 0, 0);
INSERT INTO `dede_area` VALUES (2201, '长沙市', 22, 0);
INSERT INTO `dede_area` VALUES (2202, '株州市', 22, 0);
INSERT INTO `dede_area` VALUES (2203, '湘潭市', 22, 0);
INSERT INTO `dede_area` VALUES (2204, '衡阳市', 22, 0);
INSERT INTO `dede_area` VALUES (2205, '邵阳市', 22, 0);
INSERT INTO `dede_area` VALUES (2206, '岳阳市', 22, 0);
INSERT INTO `dede_area` VALUES (2207, '常德市', 22, 0);
INSERT INTO `dede_area` VALUES (2208, '张家界市', 22, 0);
INSERT INTO `dede_area` VALUES (2209, '益阳市', 22, 0);
INSERT INTO `dede_area` VALUES (2210, '郴州市', 22, 0);
INSERT INTO `dede_area` VALUES (2211, '永州市', 22, 0);
INSERT INTO `dede_area` VALUES (2212, '怀化市', 22, 0);
INSERT INTO `dede_area` VALUES (2213, '娄底市', 22, 0);
INSERT INTO `dede_area` VALUES (2214, '湘西州', 22, 0);
INSERT INTO `dede_area` VALUES (23, '广西区', 0, 0);
INSERT INTO `dede_area` VALUES (2301, '南宁市', 23, 0);
INSERT INTO `dede_area` VALUES (2302, '柳州市', 23, 0);
INSERT INTO `dede_area` VALUES (2303, '桂林市', 23, 0);
INSERT INTO `dede_area` VALUES (2304, '梧州市', 23, 0);
INSERT INTO `dede_area` VALUES (2305, '北海市', 23, 0);
INSERT INTO `dede_area` VALUES (2306, '防城港市', 23, 0);
INSERT INTO `dede_area` VALUES (2307, '钦州市', 23, 0);
INSERT INTO `dede_area` VALUES (2308, '贵港市', 23, 0);
INSERT INTO `dede_area` VALUES (2309, '玉林市', 23, 0);
INSERT INTO `dede_area` VALUES (2310, '南宁地区', 23, 0);
INSERT INTO `dede_area` VALUES (2311, '柳州地区', 23, 0);
INSERT INTO `dede_area` VALUES (2312, '贺州地区', 23, 0);
INSERT INTO `dede_area` VALUES (2313, '百色地区', 23, 0);
INSERT INTO `dede_area` VALUES (2314, '河池地区', 23, 0);
INSERT INTO `dede_area` VALUES (24, '海南省', 0, 0);
INSERT INTO `dede_area` VALUES (2401, '海口市', 24, 0);
INSERT INTO `dede_area` VALUES (2402, '三亚市', 24, 0);
INSERT INTO `dede_area` VALUES (2403, '五指山市', 24, 0);
INSERT INTO `dede_area` VALUES (2404, '琼海市', 24, 0);
INSERT INTO `dede_area` VALUES (2405, '儋州市', 24, 0);
INSERT INTO `dede_area` VALUES (2406, '琼山市', 24, 0);
INSERT INTO `dede_area` VALUES (2407, '文昌市', 24, 0);
INSERT INTO `dede_area` VALUES (2408, '万宁市', 24, 0);
INSERT INTO `dede_area` VALUES (2409, '东方市', 24, 0);
INSERT INTO `dede_area` VALUES (2410, '澄迈县', 24, 0);
INSERT INTO `dede_area` VALUES (2411, '定安县', 24, 0);
INSERT INTO `dede_area` VALUES (2412, '屯昌县', 24, 0);
INSERT INTO `dede_area` VALUES (2413, '临高县', 24, 0);
INSERT INTO `dede_area` VALUES (2414, '白沙县', 24, 0);
INSERT INTO `dede_area` VALUES (2415, '昌江县', 24, 0);
INSERT INTO `dede_area` VALUES (2416, '乐东县', 24, 0);
INSERT INTO `dede_area` VALUES (2417, '陵水县', 24, 0);
INSERT INTO `dede_area` VALUES (2418, '保亭县', 24, 0);
INSERT INTO `dede_area` VALUES (2419, '琼中县', 24, 0);
INSERT INTO `dede_area` VALUES (25, '云南省', 0, 0);
INSERT INTO `dede_area` VALUES (2501, '昆明市', 25, 0);
INSERT INTO `dede_area` VALUES (2502, '曲靖市', 25, 0);
INSERT INTO `dede_area` VALUES (2503, '玉溪市', 25, 0);
INSERT INTO `dede_area` VALUES (2504, '保山市', 25, 0);
INSERT INTO `dede_area` VALUES (2505, '昭通市', 25, 0);
INSERT INTO `dede_area` VALUES (2506, '思茅地区', 25, 0);
INSERT INTO `dede_area` VALUES (2507, '临沧地区', 25, 0);
INSERT INTO `dede_area` VALUES (2508, '丽江地区', 25, 0);
INSERT INTO `dede_area` VALUES (2509, '文山州', 25, 0);
INSERT INTO `dede_area` VALUES (2510, '红河州', 25, 0);
INSERT INTO `dede_area` VALUES (2511, '西双版纳', 25, 0);
INSERT INTO `dede_area` VALUES (2512, '楚雄州', 25, 0);
INSERT INTO `dede_area` VALUES (2513, '大理州', 25, 0);
INSERT INTO `dede_area` VALUES (2514, '德宏州', 25, 0);
INSERT INTO `dede_area` VALUES (2515, '怒江州', 25, 0);
INSERT INTO `dede_area` VALUES (2516, '迪庆州', 25, 0);
INSERT INTO `dede_area` VALUES (26, '贵州省', 0, 0);
INSERT INTO `dede_area` VALUES (2601, '贵阳市', 26, 0);
INSERT INTO `dede_area` VALUES (2602, '六盘水市', 26, 0);
INSERT INTO `dede_area` VALUES (2603, '遵义市', 26, 0);
INSERT INTO `dede_area` VALUES (2604, '安顺市', 26, 0);
INSERT INTO `dede_area` VALUES (2605, '铜仁地区', 26, 0);
INSERT INTO `dede_area` VALUES (2606, '毕节地区', 26, 0);
INSERT INTO `dede_area` VALUES (2607, '黔西南州', 26, 0);
INSERT INTO `dede_area` VALUES (2608, '黔东南州', 26, 0);
INSERT INTO `dede_area` VALUES (2609, '黔南州', 26, 0);
INSERT INTO `dede_area` VALUES (27, '西藏区', 0, 0);
INSERT INTO `dede_area` VALUES (2701, '拉萨市', 27, 0);
INSERT INTO `dede_area` VALUES (2702, '那曲地区', 27, 0);
INSERT INTO `dede_area` VALUES (2703, '昌都地区', 27, 0);
INSERT INTO `dede_area` VALUES (2704, '山南地区', 27, 0);
INSERT INTO `dede_area` VALUES (2705, '日喀则', 27, 0);
INSERT INTO `dede_area` VALUES (2706, '阿里地区', 27, 0);
INSERT INTO `dede_area` VALUES (2707, '林芝地区', 27, 0);
INSERT INTO `dede_area` VALUES (28, '甘肃省', 0, 0);
INSERT INTO `dede_area` VALUES (2801, '兰州市', 28, 0);
INSERT INTO `dede_area` VALUES (2802, '金昌市', 28, 0);
INSERT INTO `dede_area` VALUES (2803, '白银市', 28, 0);
INSERT INTO `dede_area` VALUES (2804, '天水市', 28, 0);
INSERT INTO `dede_area` VALUES (2805, '嘉峪关市', 28, 0);
INSERT INTO `dede_area` VALUES (2806, '武威市', 28, 0);
INSERT INTO `dede_area` VALUES (2807, '定西地区', 28, 0);
INSERT INTO `dede_area` VALUES (2808, '平凉地区', 28, 0);
INSERT INTO `dede_area` VALUES (2809, '庆阳地区', 28, 0);
INSERT INTO `dede_area` VALUES (2810, '陇南地区', 28, 0);
INSERT INTO `dede_area` VALUES (2811, '张掖地区', 28, 0);
INSERT INTO `dede_area` VALUES (2812, '酒泉地区', 28, 0);
INSERT INTO `dede_area` VALUES (2813, '甘南州', 28, 0);
INSERT INTO `dede_area` VALUES (2814, '临夏州', 28, 0);
INSERT INTO `dede_area` VALUES (29, '宁夏区', 0, 0);
INSERT INTO `dede_area` VALUES (2901, '银川市', 29, 0);
INSERT INTO `dede_area` VALUES (2902, '石嘴山市', 29, 0);
INSERT INTO `dede_area` VALUES (2903, '吴忠市', 29, 0);
INSERT INTO `dede_area` VALUES (2904, '固原市', 29, 0);
INSERT INTO `dede_area` VALUES (30, '青海省', 0, 0);
INSERT INTO `dede_area` VALUES (3001, '西宁市', 30, 0);
INSERT INTO `dede_area` VALUES (3002, '海东地区', 30, 0);
INSERT INTO `dede_area` VALUES (3003, '海北州', 30, 0);
INSERT INTO `dede_area` VALUES (3004, '黄南州', 30, 0);
INSERT INTO `dede_area` VALUES (3005, '海南州', 30, 0);
INSERT INTO `dede_area` VALUES (3006, '果洛州', 30, 0);
INSERT INTO `dede_area` VALUES (3007, '玉树州', 30, 0);
INSERT INTO `dede_area` VALUES (3008, '海西州', 30, 0);
INSERT INTO `dede_area` VALUES (31, '新疆区', 0, 0);
INSERT INTO `dede_area` VALUES (3101, '乌鲁木齐', 31, 0);
INSERT INTO `dede_area` VALUES (3102, '克拉玛依', 31, 0);
INSERT INTO `dede_area` VALUES (3103, '石河子市', 31, 0);
INSERT INTO `dede_area` VALUES (3104, '吐鲁番', 31, 0);
INSERT INTO `dede_area` VALUES (3105, '哈密地区', 31, 0);
INSERT INTO `dede_area` VALUES (3106, '和田地区', 31, 0);
INSERT INTO `dede_area` VALUES (3107, '阿克苏', 31, 0);
INSERT INTO `dede_area` VALUES (3108, '喀什地区', 31, 0);
INSERT INTO `dede_area` VALUES (3109, '克孜勒苏', 31, 0);
INSERT INTO `dede_area` VALUES (3110, '巴音郭楞', 31, 0);
INSERT INTO `dede_area` VALUES (3111, '昌吉州', 31, 0);
INSERT INTO `dede_area` VALUES (3112, '博尔塔拉', 31, 0);
INSERT INTO `dede_area` VALUES (3113, '伊犁州', 31, 0);
INSERT INTO `dede_area` VALUES (3117, '东城区', 1, 0);
INSERT INTO `dede_area` VALUES (32, '香港区', 0, 0);
INSERT INTO `dede_area` VALUES (33, '澳门区', 0, 0);
INSERT INTO `dede_area` VALUES (35, '台湾省', 0, 0);

INSERT INTO `#@__task`(id, usermtools, rmpwd, tasks, typeid, startid, endid, nodes, dotime, degree) VALUES (1, 0, '', 'mhday,opdb', 0, 0, 0, '', '02:30:00', 'allday');

